(function(){function _vwo_err(e) {
    var errQuery = new URLSearchParams({
      a: "1058844",
      s: "j.php",
      _cu: window.location.href,
      e: (e && e.message ? e.message.substring(0, 1000) : "")
    }).toString();
    if (e && e.code) errQuery += "&code=" + encodeURIComponent(e.code);
    if (e && e.type) errQuery += "&type=" + encodeURIComponent(e.type);
    window.VWO.collect(`ee.gif?${errQuery}`, { path: 1 });
    if (e.cause === "archivedDomain") throw e;
  };try{var extE=0;window.VWO=window.VWO||[];window.VWO._=window.VWO._||{};window.VWO._.sE=window.VWO._.sE||function(fn){return function(){try{return fn.apply(this,arguments)}catch(err){console.error('safeExecute failed:',err)}}};/*! @fileName: tracking-endpoints.js */window.VWO._.sE(void(()=>{function n(n,i={}){if(!n)return;const w=(window.VWO._.domains||{}).cl,o=i.path?`${w}${String(n).replace(/^\/+/,"")}`:n;if(window.VWO._.enFetch)return void fetch(o,{method:"GET",keepalive:!0}).catch(()=>{});const e=new Image;e.onload=()=>{},e.onerror=()=>{},e.src=o}const i="edge.wingify.net",w="https://";window.VWO._.domains=window.VWO._.domains||{},window.VWO._.sD=n=>{const{base:o,coll:e,serve:t,dl:d=""}=n,r=document.currentScript,c=o||(null==r?void 0:r.src);window.VWO.nonce=(null==r?void 0:r.nonce)||"";const s=(()=>{if(!c)return"";try{const n=new URL(c);return o?`${n.hostname}${n.pathname.replace(/\/+$/,"")}`:n.hostname}catch(n){return""}})(),$=new URL(c).hostname===i,a=t||($?i:s),f=e||($?"collect.wingify.net":a),g=window.VWO._.domains,l=`${w}${a}`;g.sv=`${l}/`,g.serverUrl=`${l}`,g.cl=`${w}${f}/${d?d+"/":""}`,g.dl=d,g.collect=`${w}${f}/`},window.VWO.load_co=(i,w={})=>{const{path:o,defer:e,fetchPriority:t,onError:d}=w,r=(window.VWO._.domains||{}).sv,c=o?`${r}${String(i).replace(/^\/+/,"")}`:i;if(!c)return;const s=document.createElement("script");window.VWO.nonce&&(s.nonce=window.VWO.nonce),s.src=c,s.type="text/javascript",e&&(s.defer=!0),s.fetchPriority=t||"high",s.onload=()=>{},s.onerror=()=>{window.VWO._.gcpfb&&window.VWO._.gcpfb(c,window.VWO.load_co)||(d&&d(),window._vwo_err?window._vwo_err({message:`Failed to load ${c}`}):n(`e.gif?${new URLSearchParams({a:String(window._vwo_acc_id||0),s:`${window._vwo_acc_id||0}.js`,_cu:window.location.href,e:`Failed to load ${c}`}).toString()}`,{path:1}))},document.head.appendChild(s)},window.VWO.collect=n,window.VWO._.trkPaths={sn:"s.gif",vS:"l.gif",mt:"c.gif",hm:"h.gif",err:"ee.gif"}})());
;window.VWO._.sD({base:'https://dev.visualwebsiteoptimizer.com'});;(function(){window._VWO=window._VWO||{};var aC=window._vwo_code;if(typeof aC==='undefined'){window._vwo_mt='dupCode';return;}if(window._VWO.sCL){window._vwo_mt='dupCode';window._VWO.sCDD=true;try{if(aC){clearTimeout(window._vwo_settings_timer);var h=document.querySelectorAll('#_vis_opt_path_hides');var x=h[h.length>1?1:0];x&&x.remove();}}catch(e){}return;}window._VWO.sCL=true;;window._vwo_mt="live";var localPreviewObject={};var previewKey="_vis_preview"+"_"+1058844;var wL=window.location;;try{localPreviewObject[previewKey]=window.localStorage.getItem(previewKey);JSON.parse(localPreviewObject[previewKey])}catch(e){localPreviewObject[previewKey]=""}try{window._vwo_tm="";var getMode=function(e){var n;if(window.name.indexOf(e)>-1){n=window.name}else{n=wL.search.match("(?:_vwo_m|_wingify_m)=([^&]*)");n=n&&atob(decodeURIComponent(n[1]))}try{return n&&JSON.parse(n)}catch(err){return null}};var ccMode=getMode("_vwo_cc");if(window.name.indexOf("_vis_heatmap")>-1||window.name.indexOf("_vis_editor")>-1||ccMode||window.name.indexOf("_vis_preview")>-1||window.name.indexOf("_wingify_preview")>-1){try{if(ccMode){window._vwo_mt=decodeURIComponent(wL.search.match("(?:_vwo_m|_wingify_m)=([^&]*)")[1])}else if(window.name&&JSON.parse(window.name)){window._vwo_mt=window.name}}catch(e){if(window._vwo_tm)window._vwo_mt=window._vwo_tm;if(window._vwo_acc_id===1058844&&localPreviewObject[previewKey]){window._vwo_mt=JSON.stringify(localPreviewObject)}}}else if(window._vwo_tm.length){window._vwo_mt=window._vwo_tm}else if(location.href.indexOf("_vis_opt_preview_combination")!==-1&&location.href.indexOf("_vis_test_id")!==-1){window._vwo_mt="sharedPreview"}else if(localPreviewObject[previewKey]){window._vwo_mt=JSON.stringify(localPreviewObject)}else if(location.href.indexOf("wingify_qa_assistant=true")!==-1){window._vwo_mt=JSON.stringify({[previewKey]:"wingify_qaa"});const url=new URL(window.location.href);url.searchParams.delete("wingify_qa_assistant");window.history.replaceState({},"",url)}if(window._vwo_mt!=="live"){;if(typeof extE!=="undefined"){extE=1}if (!getMode("_vwo_cc")) {
        // This Preview Code is supposed to execute Async Smart Code that further takes care of heatmap/preview/editor
        (function(){var cParam='';try{if(window.VWO&&window.VWO.appliedCampaigns){var campaigns=window.VWO.appliedCampaigns;for(var cId in campaigns){if(campaigns.hasOwnProperty(cId)){var v=campaigns[cId].v;if(cId&&v){cParam='&c='+cId+'-'+v+'-1';break;}}}}}catch(e){};window._vwo_prevMode=false;_vwo_code.load(window.VWO._.domains.sv + 'j.php?mode='+encodeURIComponent(window._vwo_mt)+'&a=1058844&f=1&u='+encodeURIComponent(window._vis_opt_url||document.URL)+'&eventArch=true'+'&x=true'+cParam,{sL:window._vwo_code.sL});if(window._vwo_code.sL){window._vwo_prevMode=true;}})();;
      } else {
        (function () {
          window._vwo_code && window._vwo_code.finish();;
          _vwo_ccc = { u: window.VWO._.domains.sv + 'j.php?a=1058844&u=https%3A%2F%2Floft.com.br%2F&vn=2.2&x=true' };
          // var app = getMode("_vwo_cc")._vwo_cc.app || "app";
          var s = document.createElement("script");
          s.src = "https://dev.visualwebsiteoptimizer.com/cdn/edrv/beta/checker-d6466a772fa38d63031d87bb570ad916.js";
          document.head.appendChild(s);
        })();
      }}}catch(e){var vwo_e=new Image;vwo_e.src="https://dev.visualwebsiteoptimizer.com/ee.gif?s=mode_det&e="+encodeURIComponent(e&&e.stack&&e.stack.substring(0,1e3)+"&vn=");aC&&_vwo_code.finish();}})();
;window._vwo_cookieDomain="loft.com.br";if(window._vwo_mt === "live"){window.VWO=window.VWO||[];window._vwo_acc_id=1058844;window.VWO._=window.VWO._||{};;const shouldSampleApm=false;if(shouldSampleApm){setTimeout((function(){VWO.load_co(window.VWO._.domains.sv+"cdn/apmLib-.br.js")}),0)}VWO._=VWO._||{};var visMeta=VWO._.visMeta;VWO._.allSettings=function(){return{dataStore:{events:{}}}}();window.VWO.visUuid="D3B80214A25DB222D6E8D9A424BA9360F|5ce7264bc75bae6d98964137b66ec5be";
;_vwo_code.sT=_vwo_code.finished();(function(c,a,e,d,b,z,g,sT){if(window.VWO._&&window.VWO._.isBot)return;const cookiePrefix=window._vwoCc&&window._vwoCc.cookiePrefix||"";const useLocalStorage=sT==="ls";const cookieName=cookiePrefix+"_vwo_uuid_v2";const escapedCookieName=cookieName.replace(/([.*+?^${}()|[\]\\])/g,"\\$1");const cookieDomain=g;function getValue(){if(useLocalStorage){return localStorage.getItem(cookieName)}else{const regex=new RegExp("(^|;\\s*)"+escapedCookieName+"=([^;]*)");const match=e.cookie.match(regex);return match?decodeURIComponent(match[2]):null}}function setValue(value,days){if(useLocalStorage){localStorage.setItem(cookieName,value)}else{e.cookie=cookieName+"="+value+"; expires="+new Date(864e5*days+ +new Date).toGMTString()+"; domain="+cookieDomain+"; path=/"}}let existingValue=null;if(sT){const cookieRegex=new RegExp("(^|;\\s*)"+escapedCookieName+"=([^;]*)");const cookieMatch=e.cookie.match(cookieRegex);const cookieValue=cookieMatch?decodeURIComponent(cookieMatch[2]):null;const lsValue=localStorage.getItem(cookieName);if(useLocalStorage){if(lsValue){existingValue=lsValue;if(cookieValue){e.cookie=cookieName+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT; domain="+cookieDomain+"; path=/"}}else if(cookieValue){localStorage.setItem(cookieName,cookieValue);e.cookie=cookieName+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT; domain="+cookieDomain+"; path=/";existingValue=cookieValue}}else{if(cookieValue){existingValue=cookieValue;if(lsValue){localStorage.removeItem(cookieName)}}else if(lsValue){e.cookie=cookieName+"="+lsValue+"; expires="+new Date(864e5*366+ +new Date).toGMTString()+"; domain="+cookieDomain+"; path=/";localStorage.removeItem(cookieName);existingValue=lsValue}}a=existingValue||a}else{const regex=new RegExp("(^|;\\s*)"+escapedCookieName+"=([^;]*)");const match=e.cookie.match(regex);a=match?decodeURIComponent(match[2]):a}if(-1==e.cookie.indexOf("_vis_opt_out")&&-1==d.location.href.indexOf("vwo_opt_out=1")){window.VWO.visUuid=a;a=a.split("|");var vQuery="cd="+(window._vis_opt_cookieDays||0)+"&a=1058844&d="+encodeURIComponent(d.location.hostname.replace(/^www\./,"") || c)+"&u="+a[0]+"&h="+a[1]+"&t="+z;;window.VWO.collect("collect/v.gif?"+vQuery,{path:1,pushToIeQueue:1});setValue(a.join("|"),366)}})("loft.com.br",window.VWO.visUuid,document,window,0,_vwo_code.sT,"loft.com.br","false"||null);
;;window.VWO=window.VWO||[];(function(){function l(e){return e.replace(/[^\w\s-.][\w]/g,(function(e){return e.toUpperCase()})).replace(/[^\w\s-.]/g,"").replace(/ [\w]/g,(function(e){return e.toUpperCase()})).replace(/ /g,"")}function i(e,t){if("object"!=typeof t||Array.isArray(t))return u("Invalid attribute type: attribute can only be an object!");var n,r,a,o={};for(n in t)if(Object.prototype.hasOwnProperty.call(t,n)){var i="props"===(i=(i=l((i=n).slice(i.search(/[\w-.]/g)))).replace(/^(_|vwo_|\.|v_|i_|-)*/g,""))?"":i;if(!i.trim())return u("Invalid attribute name: "+n+" is not allowed as an attribute name!");40<i.length&&(i=i.slice(0,40),console.warn("Attribute name should not be greater than 40 characters!"));var c=s(t[n])||(c=t[n],"[object Array]"===toString.call(c))?JSON.stringify(t[n]):t[n];v(e)||(a=100,c=(r=c).length>a?r.slice(0,a-1)+"...":r),o[i]=c}return o}function s(e){return"[object Object]"===toString.call(e)}function u(e){console.log("%cVWO Event API Error:","font-weight:bold;",e),_vwo_err({message:e})}function c(e=-1,t=""){switch(e){case 0:return u("Event name cannot be empty!");case 1:return console.warn("Event name should not be greater than 40 characters!");case 2:return u("Invalid event name: "+t+" is not allowed as an event name!");default:return u("Invalid event name: event name can only be a string!")}}function r(e,t,n){var e=((e,t)=>{var n;return"string"!=typeof e?c():(e=e.trim())?(e=(e=>("visitors"===(e=(e=l(e.slice(e.search(/[\w-.]/g)))).replace(/^(_|vwo_|\.|v_|i_|-)*/g,"")).toLowerCase()&&(e+="_1"),e))(n=e))?(40<e.length&&(c(1),e=e.slice(0,40)),(n=i(e,t))?{eventName:e,filteredAttributeObject:n}:void 0):c(2,n):c(0)})(e,t=t||{}),r={ogName:1,source:1};if(!e)return{filteredData:void 0,cb:null};t=null;if(s(n)){"function"==typeof n.cb&&(t=n.cb),delete n.cb;var a,o={};for(a in n)r[a]&&(o[a]=n[a]);0<Object.keys(o).length&&(e.filteredAttributeObject.vwoMeta=o)}return{filteredData:e,cb:t}}function v(e){return window.VWO._&&VWO._.allSettings&&VWO._.allSettings.dataStore&&VWO._.allSettings.dataStore.events&&VWO._.allSettings.dataStore.events[e]}VWO.event=function(e,t,n){var{filteredData:e,cb:n}=r(e,t,n);if(e&&(e=>{if(!window._vis_debug&&!v(e)){var t;try{t=JSON.parse(window.localStorage.getItem("vwoUnRegEvents"))||{}}catch(e){t={}}if(t[e])return!1;t[e]=!0;e=JSON.stringify(t);window.localStorage.setItem("vwoUnRegEvents",e)}return!0})(e.eventName))return window._vis_debug?void 0:((t={d:{event:{}}}).d.event.props=e.filteredAttributeObject||{},t.d.event.props.page={title:document.title,url:window._vis_opt_url||window.location.href,referrerUrl:document.referrer},t.d.event.name=e.eventName,t.d.event.time=Date.now(),e="https://dev.visualwebsiteoptimizer.com/events/"+(v(e.eventName)?"t":"t/u")+"?en="+e.eventName+"&a="+1058844+"&_cu="+encodeURIComponent(document.URL),navigator.sendBeacon(e,JSON.stringify(t)),void("function"==typeof n&&n()))}})();
;for(var e=0;e<window.VWO.length;e++){exC(window.VWO[e])}window.VWO.push=function(){exC(arguments[0])};function exC(a){if(!Array.isArray(a))return;switch(a[0]){case"onVWOLoaded":var p=[];p[0]={};p[1]=[];return a[1].call(this,p);case"onVWOCampaignsLoaded":return a[1].call(this,{bucketed_campaigns:[]});case"event":return VWO.event(a[1],a[2],a[3])}}
;_vwo_code.finish();}}catch(e){_vwo_code.finish();;_vwo_err(e);window.VWO.caE=1}})();
